// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Predicts flight delays with a probability and estimated delay time.
 *
 * - predictFlightDelay - Predicts flight delays.
 * - PredictFlightDelayInput - The input type for the predictFlightDelay function.
 * - PredictFlightDelayOutput - The return type for the predictFlightDelay function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PredictFlightDelayInputSchema = z.object({
  flightNumber: z.string().describe('The flight number to predict delay for.'),
  airportCode: z.string().describe('The airport code (e.g., EBB) of the flight.'),
  currentDateTime: z.string().describe('The current date and time in ISO format.'),
});

export type PredictFlightDelayInput = z.infer<typeof PredictFlightDelayInputSchema>;

const PredictFlightDelayOutputSchema = z.object({
  delayProbability: z
    .number()
    .min(0)
    .max(1)
    .describe('The probability of a delay, between 0 and 1.'),
  estimatedDelayTimeMinutes: z
    .number()
    .min(0)
    .describe('The estimated delay time in minutes.'),
  explanation: z
    .string()
    .describe('The explanation of predicted delay time and probability.'),
});

export type PredictFlightDelayOutput = z.infer<typeof PredictFlightDelayOutputSchema>;

export async function predictFlightDelay(input: PredictFlightDelayInput): Promise<PredictFlightDelayOutput> {
  return predictFlightDelayFlow(input);
}

const predictFlightDelayPrompt = ai.definePrompt({
  name: 'predictFlightDelayPrompt',
  input: {schema: PredictFlightDelayInputSchema},
  output: {schema: PredictFlightDelayOutputSchema},
  prompt: `You are an expert in predicting flight delays at Entebbe Airport.
  Given the flight number {{flightNumber}}, the airport code {{airportCode}}, and the current date and time {{currentDateTime}}, predict the probability of a delay and the estimated delay time in minutes.
  Return a JSON object with the following format:
  {
    "delayProbability": 0.0,
    "estimatedDelayTimeMinutes": 0,
    "explanation": ""
  }
  The probability should be between 0 and 1, and the estimated delay time should be in minutes.
  Explain the reasons for delay in the explanation field.
  `,
});

const predictFlightDelayFlow = ai.defineFlow(
  {
    name: 'predictFlightDelayFlow',
    inputSchema: PredictFlightDelayInputSchema,
    outputSchema: PredictFlightDelayOutputSchema,
  },
  async input => {
    const {output} = await predictFlightDelayPrompt(input);
    return output!;
  }
);
