// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates maintenance schedules based on predictive algorithms incorporating airline preferences.
 *
 * - provideMaintenanceSchedules - A function that generates maintenance schedules.
 * - ProvideMaintenanceSchedulesInput - The input type for the provideMaintenanceSchedules function.
 * - ProvideMaintenanceSchedulesOutput - The return type for the provideMaintenanceSchedules function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ProvideMaintenanceSchedulesInputSchema = z.object({
  aircraftType: z.string().describe('The type of aircraft.'),
  airlinePreferences: z.string().describe('The airline\u2019s specific maintenance preferences and priorities.'),
  incomingAircraftData: z.string().describe('The stream of incoming aircraft systems and sensor data.'),
});
export type ProvideMaintenanceSchedulesInput = z.infer<
  typeof ProvideMaintenanceSchedulesInputSchema
>;

const ProvideMaintenanceSchedulesOutputSchema = z.object({
  maintenanceSchedule: z
    .string()
    .describe('The generated maintenance schedule.'),
});
export type ProvideMaintenanceSchedulesOutput = z.infer<
  typeof ProvideMaintenanceSchedulesOutputSchema
>;

export async function provideMaintenanceSchedules(
  input: ProvideMaintenanceSchedulesInput
): Promise<ProvideMaintenanceSchedulesOutput> {
  return provideMaintenanceSchedulesFlow(input);
}

const maintenanceSchedulerTool = ai.defineTool({
  name: 'maintenanceScheduler',
  description: 'Schedules aircraft maintenance based on aircraft data and airline preferences.',
  inputSchema: ProvideMaintenanceSchedulesInputSchema,
  outputSchema: ProvideMaintenanceSchedulesOutputSchema,
},
async (input) => {
  return {
    maintenanceSchedule: `Maintenance schedule generated for ${input.aircraftType} based on predictive algorithms and airline preferences.`
  };
});

const prompt = ai.definePrompt({
  name: 'provideMaintenanceSchedulesPrompt',
  tools: [maintenanceSchedulerTool],
  input: {schema: ProvideMaintenanceSchedulesInputSchema},
  output: {schema: ProvideMaintenanceSchedulesOutputSchema},
  prompt: `You are a maintenance schedule generator. You have access to a tool that generates maintenance schedules.

The current aircraft type is {{{aircraftType}}}.
The airline preferences are {{{airlinePreferences}}}.
The stream of incoming aircraft systems and sensor data is {{{incomingAircraftData}}}.

Generate a maintenance schedule using the maintenanceSchedulerTool.
`,
});

const provideMaintenanceSchedulesFlow = ai.defineFlow(
  {
    name: 'provideMaintenanceSchedulesFlow',
    inputSchema: ProvideMaintenanceSchedulesInputSchema,
    outputSchema: ProvideMaintenanceSchedulesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
